import click
import os
import pandas as pd
import numpy as np

from boostdm.globals import INTOGEN_DATASETS
sat_datasets = os.path.join(INTOGEN_DATASETS, 'steps/boostDM/saturation')


def mimic_explode(s):
    """Mimics the behavior of Series.explode() for older pandas versions."""
    # Get the length of each list to know how many times to repeat the index
    # (fillna(1) ensures that rows with NaN/missing values aren't accidentally deleted)
    lens = s.str.len().fillna(1).astype(int)
    
    # Flatten the lists into a single 1D array
    # If a value isn't a list (like NaN), wrap it in a list so it flattens correctly
    flat_data = [item for sublist in s for item in (sublist if isinstance(sublist, list) else [sublist])]
    
    # Rebuild the Series with the repeated index
    return pd.Series(flat_data, index=s.index.repeat(lens))


def residue_to_genomic(df):

    """
    From an input file with the significant genes and residues from oncodrive3d output of type *.o3d_genes.tsv, 
    this function generates a dataframe with the genomic coordinates of significantly 3D clustered residues.
    """

    dg = df.copy()
    
    dh = {'HUGO Symbol': [], 'chromosome': [], 'genomic position': [], 'CANCER_TYPE': []}
    
    for gene, ttype in dg.groupby(['Gene', 'CANCER_TYPE']).size().index:
        try:
            residues = dg[(dg['Gene'] == gene) & (dg['CANCER_TYPE'] == ttype)]['C_pos'].values[0]
            residues = list(map(int, residues.strip(" []").split()))
            saturation = pd.read_csv(f"{sat_datasets}/{gene}.vep.gz", sep='\t')
            saturation['Protein_position'] = saturation['Protein_position'].astype(str)
            saturation = saturation[saturation['Protein_position'] != '-']
            saturation['Protein_position'] = saturation['Protein_position'].astype(int)
            genomic_coordinates = saturation[saturation['Protein_position'].isin(residues)][['Chromosome', 'Position']].drop_duplicates()
            dh['HUGO Symbol'].extend([gene])
            dh['chromosome'].extend([str(genomic_coordinates['Chromosome'].iloc[0])])
            dh['genomic position'].extend([','.join(map(str, genomic_coordinates['Position'].values))])
            dh['CANCER_TYPE'].extend([ttype])
        except FileNotFoundError:
            print(f"Saturation file for gene {gene} not found.")
            continue
    dh = pd.DataFrame(dh)
    return dh


def expand_genomic_coordinates_newpandas(df):
    
    """
    From a dataframe with the genomic coordinates of significantly 3D clustered residues
    per gene and tumor type, as generated by the function residue_to_genomic, 
    this function generates a dataframe with one row per genomic coordinate.
    """

    dk = (df.set_index(['HUGO Symbol', 'CANCER_TYPE'])
            .apply(lambda x: mimic_explode(x.str.split(',')))
            .reset_index())
    dk.rename(columns={'genomic position': 'pos'}, inplace=True)
    dk = dk[['chromosome', 'pos', 'CANCER_TYPE']]
    return dk


def expand_genomic_coordinates(dh):

    """
    From a dataframe with the genomic coordinates of significantly 3D clustered residues
    per gene and tumor type, as generated by the function residue_to_genomic, 
    this function generates a dataframe with one row per genomic coordinate.
    """

    cols_to_split = ['genomic position']  # Update this to the actual column(s) containing the commas

    # 1. Split the strings into lists for the target columns
    split_series = dh[cols_to_split[0]].astype(str).str.split(',')

    # 2. Figure out how many items are in each list (this is our multiplier)
    lens = split_series.str.len().fillna(1).astype(int)

    # 3. Repeat the ENTIRE dataframe's rows based on those lengths
    result_df = dh.loc[dh.index.repeat(lens)].copy()

    # 4. Flatten the lists and overwrite the columns in the repeated dataframe
    for col in cols_to_split:
        # Split the column
        s = dh[col].astype(str).str.split(',')
        # Flatten it
        flat_data = [item for sublist in s for item in (sublist if isinstance(sublist, list) else [sublist])]
        # Assign it back
        result_df[col] = flat_data

    result_df.rename(columns={'genomic position': 'pos'}, inplace=True)
    result_df = result_df[['chromosome', 'pos', 'CANCER_TYPE']]
    
    return result_df


@click.command()
@click.option('--input', type=click.Path(), help='Input file')
@click.option('--output', type=click.Path(), help='Output file')
def cli(input, output):

    print(input)
    df = pd.read_csv(input, sep='\t', header=0)
    dh = residue_to_genomic(df)
    dk = expand_genomic_coordinates(dh)
    dk.to_csv(output, sep='\t', index=False, compression='gzip')


if __name__ == '__main__':
    cli()