Bootstrap: docker
From: debian:buster-slim

%environment
    export LC_ALL=C.UTF-8
    export BGDATA_OFFLINE=TRUE

%setup
    mkdir ${SINGULARITY_ROOTFS}/boostdm
    cp boostwrap-develop.zip ${SINGULARITY_ROOTFS}/boostdm/
    cp runner.sh ${SINGULARITY_ROOTFS}/usr/bin
    chmod a+rx ${SINGULARITY_ROOTFS}/usr/bin/runner.sh

%post
    apt-get update
    apt-get -y install locales-all \
    zlib1g-dev \
    python3 \
    python3-dev \
    python3-pip \
    python3-dill \
    python3-numpy \
    python3-pandas \
    python3-sklearn \
    python3-pycurl \
    python3-pybedtools \
    python3-pybigwig \
    python3-matplotlib \
    python3-click \
    python3-tqdm \
    python3-pygraphviz \
    python3-networkx \
    tabix \
    bedtools

    rm -rf /var/lib/apt/lists/*

    /usr/bin/pip3 install xgboost==0.90 \
    shap==0.35 \
    ipython \
    pillow \
    bgreference \
    pytabix==0.0.2 \
    bgvep \
    pyliftover \
    scikit-optimize \
    seaborn \
    bgoncotree

    /usr/bin/pip3 install /boostdm/boostwrap-develop.zip

