
process {

    time = 12.h
    queue = 'bbg_cpu_zen4'

    withName: CreateDatasets {
        memory = 20.GB
    }

    withName: SplitCVMetacohort {
        cpus = 24
    }

    withName: TrainingMeta {
        cpus = 4
        memory = 20.GB
    }

    withName: CrossValidation {
        memory = 20.GB
    }

    withName: PredictSaturation {
        memory = 32.GB
    }

}


executor {
    
    name = 'slurm'
    queueSize = 100

}
